### ISSUE TITLE
Run ktlint on save

### ISSUE THREAD

**Issue by NikolayMetchev** [nbadal/ktlint-intellij-plugin#125]
It would be nice if it did really automatically format your code every time a file is saved.

**Comment by FloEdelmann** [comment]
It would also be useful to have the option to only run the linter on save (and not while typing), so that temporary lint errors during coding are not immediately reported.

E.g. hitting enter to write a new function may temporarily result in two consecutive newlines, but the resulting `no-consecutive-blank-lines` lint error is distracting.

**Comment by nbadal** [comment]
I'll see what options I have here, but it would honestly be nice to elevate this request up to the IDE level and have the ability to set a "debounce"/"cooldown" for how often the IDE runs analysis plugins in general!

**Comment by gad2103** [comment]
any news on this?

**Comment by paul-dingemans** [comment]
The upcoming version of the plugin has a some good improvements on this. As long as any errors are found, for example compilation failures, the ktlint formatting will not run. I have been using a development version of the plugin with this feature and I am very pleased with it.
