### ISSUE TITLE
Setting Disabled Rules (`--disabled_rules`) to `standard` doesn't disable standard rules

### ISSUE THREAD

**Issue by 0x6675636b796f75676974687562** [nbadal/ktlint-intellij-plugin#292]
I'm running the plug-in with the following settings:

![image](https://user-images.githubusercontent.com/73111822/225674334-32249809-47ef-4c28-ad1b-71697a27f65a.png)

Setting the _Disabled Rules_ field value to "standard" would effectively disable _KtLint_, but, apparently, it does not.

 * Plug-in version: **0.11.0**
 * IDEA version: **2022.2.4** (Build #IU-222.4459.24)

**Comment by nbadal** [comment]
@0x6675636b796f75676974687562 I'm trying to replicate this functionality with the CLI plugin (`--disabled_rules standard`) but I'm seeing the same behaviour there.

For the most part, I'm trying to keep functional parity with the command line for each setting, but perhaps disabling a ruleset can be a separate field.  Otherwise, please let me know if there's a way to do this on the command line that I'm missing!

**Comment by 0x6675636b796f75676974687562** [comment]
@nbadal, thank you for your response.

I believe you should use `--disabled_rules=standard`, not `--disabled_rules standard`:

```console
      --disabled_rules=<disabledRules>
                        Comma-separated list of rules to globally disable. To
                          disable standard ktlint rule-set use
                          --disabled_rules=standard
```

**Comment by paul-dingemans** [comment]
Property `disabled_rules` will be removed from the plugin with upcoming release. Disabling rules is now only possible by setting the appropriate `.editorconfig` property.
