### ISSUE TITLE
Unintuitive behavior of "save action" checkbox

### ISSUE THREAD

**Issue by Vampire** [nbadal/ktlint-intellij-plugin#384]
When having ktlint 0.20.0-beta-4 enabled on a project and going to the "save actions", unchecking ktlint formatting there, it is disabled completely for the project. This for me is pretty unexpected / unintuitive.

If you can make the ktlint option not shown on the on-save actions, or maybe better disabled if possible so that is just shows the status, this might be better.

If this is not possible, maybe some message could be displayed that this will disable ktlint completely for the project?

**Comment by paul-dingemans** [comment]
When refactoring the plugin, I have removed the option to enable/disable formatting on save partly but did not refactor the on-save-actions dialog. I have reverted this behavior as I now can see the value of it. In all my personal/work projects, I have added ktlint to the build pipelines and in that case it does not make sense to disable format on save as it increases the risk that the build pipeline will fail at a later stage. But when using the plugin as an optional tool, it can make sense to disable it, so that formatting is only invoked whenever explicitly invoked.
