### ISSUE TITLE
Add option to autocorrect a single violation

### ISSUE THREAD

**Issue by paul-dingemans** [nbadal/ktlint-intellij-plugin#482]
If a violation can be autocorrected, then offer a possibility to autocorrect that specific violation only.

Blocked by #385

**Comment by QuinnBast** [comment]
I'm going to assume this is what I need.

For more details, when using "Manual" mode, the plugin is able to detect violations, but there is no Alt+Enter context menu to automatically fix that violation.

![image](https://github.com/nbadal/ktlint-intellij-plugin/assets/22599103/c4046676-a75f-485b-84e4-d7ce5f3ef939)

In the "Unofficial" version of the plugin, it would highlight potential issues (like in the screenshot), but the Alt+Enter menu would allow you to auto-fix any fixable issues. Since this no longer exists I had to use "Distract Free" mode - but personally, I prefer Manual mode.

**Comment by paul-dingemans** [comment]
Please see https://github.com/nbadal/ktlint-intellij-plugin/issues/492#issuecomment-2019962905 why the Alt+Enter option was removed.

**Comment by paul-dingemans** [comment]
Closed by #533
