### ISSUE TITLE
Configure severity

### ISSUE THREAD

**Issue by tonfido** [nbadal/ktlint-intellij-plugin#539]
Thank you very much for the plugin. 

I configured my IDE in a way, that every warning is yellow on a dark background. With ktlint, style violations are threaded as warning and therefore my IDE is all yellow while typing. 

I'd like to change the severity, so I can adjust how the errors are visual presented. Is there any option already available to do so?
For e.g. eslint, I could change the inspection profile and assign a severity.

![image](https://github.com/nbadal/ktlint-intellij-plugin/assets/135229514/2184d250-3bdb-491f-be6b-5c62f92c7e44)

Would be nice, if the ktlint violations would appear similar to the eslint inspections in the inspection settings.

**Comment by paul-dingemans** [comment]
No, setting the severty level is not supported by the plugin. 

Once, you have configured ktlint, it is advised to run the plugin in `distract free` mode so that all violations which can be autocorrect will never be visible at all. The remaining violations which can not be autocorrected should be handled as an error.

Running the plugin in `manual` results in violations to be shown as warning.
