### ISSUE TITLE
[Request] Add option to only format lines changed

### ISSUE THREAD

**Issue by fgeck** [nbadal/ktlint-intellij-plugin#593]
Hey,

thank you very much for the great plugin and the huge support on it.

I would highly appreciate to have a mode that only reformats lines of code a user adds/changes.
I like this approach, as it allows to work in a 'Distract free' mode but it does not reformat the whole file which would introduce too many changes in the legacy code.

If I would have to formulate some kind of acceptance criteria:

- [ ] offer user an option to in the plugin settings to change the mode to "Distract free (changed lines only)" 
- [ ] if this mode is activated automatically evaluate lines changed/introduced
- [ ] if this mode is activated automatically check rules and reformat the evaluated lines

**Comment by paul-dingemans** [comment]
Thanks for your suggestion. 

Personally, I would do one massive reformat. It will be a huge change set, but you will get the immediate benefit that all your code looks more consistent and becomes better readable.

Otherwise, you can try the [baseline](https://pinterest.github.io/ktlint/latest/install/cli/#violation-reporting) functionality of ktlint. All violations recorded in this file will be suppressed automatically. It will not work 100% as it uses line/column offsets, but it might suppress most violations on unchanged code lines.

I would not know how to implement the feature as you suggest within reasonable efforts. So I will close the issue.
