### ISSUE TITLE
Use Intellij built-in code formatter

### ISSUE THREAD

**Issue by mlthlschr** [nbadal/ktlint-intellij-plugin#8]
It would be great to integrate the plugin with the built-in code formatter (CTRL-ALT-L). This would not only be easier regarding the shortcut, but would also give the possibility of checking "reformat code" when commiting code and reformat it automatically.

As an example, the plugin of [prettier](https://github.com/JetBrains/intellij-plugins/tree/master/prettierJS) in the world of javascript is capable of doing so.

**Comment by nbadal** [comment]
Good idea! And thanks for the example link! 
I'll take a look at the viability of this for the next update (0.4.0 is being submitted today) :)

**Comment by nbadal** [comment]
Implemented here 😁 
https://github.com/nbadal/ktlint-intellij-plugin/commit/a8f08ebbf73b2ad13e315ad6f48817c7d1c8b910

Be wary though, even with "Reformat" during a commit, not all ktlint rules are auto-fixed by the tool itself. Some need to be manually fixed, such as `no-wildcard-imports` for example

**Comment by mlthlschr** [comment]
Wow, that was quick! :-D Thanks for that, I am going to take a look at it. 

The `no-wildcard-imports` issue goes a little bit deeper, right? I know that you can set this setting in the intellij code formatting options, maybe it is possible to trigger it somehow?

**Comment by nbadal** [comment]
Yeah for that one specifically there's a few IDE settings to turn off the wildcard threshold in `Settings > Editor > Code Style > Kotlin > 'Imports' Tab`

The command line utility for ktlint has a flag to set some IntelliJ settings, which might include that, but I'm holding off on implementing that part because I think they're talking about transitioning to an `.editorconfig`-based solution soon.

One improvement I might make as well is to turn off the "Format with ktlint" action for rules that are not auto-correctable.

**Comment by nbadal** [comment]
Closing since this particular issue is merged and ready for 0.5.0, but happy to continue the discussion 😁
